networks:
  key-controler:
    name: key-controller-network
    external: true
    # Use a custom driver which takes special options
    ipam:
      config:
        - subnet: 172.24.0.0/16
services:
  app:
    container_name: front-and
    restart: always
    build: .
    # ports:
    #   - "3000:3000"
    networks:
      key-controler:
        ipv4_address: 172.24.0.150
      
       
