networks:
  key-controler:
    name: keycontrollerbackend_backend
    external: true
    # Use a custom driver which takes special options
    ipam:
      config:
        - subnet: 172.29.0.0/24
services:
  app:
    container_name: front-and
    restart: always
    build: .
    ports:
      - "3000:3000"
    networks:
      key-controler:
        ipv4_address: 172.29.0.150
      
       